[project]
name = "murder-mystery-be"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "gunicorn>=23.0.0",
    "uvicorn>=0.35.0",
]
